---
title: "Mixing score on simulated data"
output: html_document
---

```{r}
source("mixing_score_functions.R")
```


### Uniform mixing

Can uniform mixing exist with different sample sizes?

```{r}
sim_uniform <- function(i) {
  x = seq(1, i, 2)
  a <- list(x = x, y = rep(x = 1, length(x)))
  x = x + 1
  b <- list(x = x, y = rep(x = 1, length(x)))
  
  return(list(a = a, b = b))
}
```

Uniform distribution of a and b

```{r}
ab <- sim_uniform(100)
a <- ab[["a"]]
b <- ab[["b"]]
plot(a, type = "n", xlab = "X", ylab = "Y")
lines(a, col="red", type = "p")
lines(b, col="blue", type = "p", pch = 4)
```


### Random mixing


```{r}
sim_random <- function(i, j) {
  x = sample(x = seq(1, 101),
             size = i,
             replace = T)
  a <- list(x = x, y = rep(x = 1, length(x)))
  x = sample(x = seq(1, 100),
             size = j,
             replace = T)
  b <- list(x = x, y = rep(x = 1, length(x)))
  
  return(list(a = a, b = b))
}
```

Random distribution of a and b

```{r}
ab <- sim_random(100, 50)
a <- ab[["a"]]
b <- ab[["b"]]
plot(a, type = "n", xlab = "X", ylab = "Y")
lines(a, col="red", type = "p")
lines(b, col="blue", type = "p", pch = 4)
```

### No mixing

```{r}
sim_no <- function(i, j) {
  x = sample(x = seq(1, 35),
             size = i,
             replace = T)
  a <- list(x = x, y = rep(x = 1, length(x)))
  x = sample(x = seq(65, 101),
             size = j,
             replace = T)
  b <- list(x = x, y = rep(x = 1, length(x)))
  
  return(list(a = a, b = b))
}
```

Random distribution of a and b

```{r}
ab <- sim_no(100, 50)
a <- ab[["a"]]
b <- ab[["b"]]
plot(a, type = "n", xlab = "X", ylab = "Y", xlim = c(1, 101))
lines(a, col="red", type = "p")
lines(b, col="blue", type = "p", pch = 4)
```

=================

```{r}
set.seed(1)
ab <- sim_no(21, 50)
set.seed(2)
cd <- sim_random(100, 50)
# ab <- sim_uniform(100)
a <- ab[["a"]]
b <- ab[["b"]]

c <- cd[["a"]]
d <- cd[["b"]]

plot(a, type = "n", xlab = "X", ylab = "Y", xlim = c(1, 101))
lines(a, col="red", type = "p")
lines(b, col="blue", type = "p", pch = 4)
lines(c, col="green", type = "p", pch = 4)
lines(d, col="violet", type = "p", pch = 5)
```



```{r}
a <- as.data.frame(x = c(a, clone = "x"))
b <- as.data.frame(x = c(b, clone = "y"))
c <- as.data.frame(x = c(c, clone = "z"))
d <- as.data.frame(x = c(d, clone = "zz"))
clone_df <- rbind(a, b, c, d)
embedding <- clone_df[,dims]
clone_df <- clone_df["clone"]
```


```{r}
MixingScoreClones(
  embedding,
  k_frac = 0.3,
  clone_df,
  cores = 1,
  clone_id = "clone"
)
```

========

On real data

279 clones (>= 8 cells), k=0.3, 20 PCs, 5 cores: 1.3 min

```{r}
clones <- bcr_cpg@meta.data %>%
  filter(clone_id != "No_contig") %>%
  count(clone_id) %>%
  arrange(desc(n)) %>%
  filter(n >= 8) %>%
  pull(clone_id)

start <- Sys.time()
set.seed(1)
MixingScoreSeurat(object = bcr_cpg, clones = clones, clone_id = "clone_id", cores = 5, k = 0.3)

end <- Sys.time()
end - start
```


